name: Frontend Deployment

on:
  push:
    branches: [ "main" ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Frontend
        working-directory: ./client
        run: |
          npm ci
          npm run build

      - name: Deploy Frontend to Vercel
        run: |
          url="$(vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }})"
          # --prebuilt seçeneği, build edilmiş bir projeyi deploy etmek için kullanılır.
          #   şu anda build işlemi vercel sunucularında yapılıyor.
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" notetut.vercel.app 